/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-103601-gb35653d4c4-20210912"
#endif /* AVUTIL_FFVERSION_H */
